// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remotedb.proto

package com.wangao.dd.protohelper;

public interface KeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:KeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * 使用 Any 类型作为值的容器，以支持不同类型的值
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * 使用 Any 类型作为值的容器，以支持不同类型的值
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
