// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remotedb.proto

package com.wangao.dd.protohelper;

public interface MyMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .KeyValue entry = 1;</code>
   */
  java.util.List<com.wangao.dd.protohelper.KeyValue> 
      getEntryList();
  /**
   * <code>repeated .KeyValue entry = 1;</code>
   */
  com.wangao.dd.protohelper.KeyValue getEntry(int index);
  /**
   * <code>repeated .KeyValue entry = 1;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .KeyValue entry = 1;</code>
   */
  java.util.List<? extends com.wangao.dd.protohelper.KeyValueOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .KeyValue entry = 1;</code>
   */
  com.wangao.dd.protohelper.KeyValueOrBuilder getEntryOrBuilder(
      int index);
}
