// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remotedb.proto

package com.wangao.dd.protohelper;

public interface RemoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MyMap data = 1;</code>
   */
  java.util.List<com.wangao.dd.protohelper.MyMap> 
      getDataList();
  /**
   * <code>repeated .MyMap data = 1;</code>
   */
  com.wangao.dd.protohelper.MyMap getData(int index);
  /**
   * <code>repeated .MyMap data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .MyMap data = 1;</code>
   */
  java.util.List<? extends com.wangao.dd.protohelper.MyMapOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .MyMap data = 1;</code>
   */
  com.wangao.dd.protohelper.MyMapOrBuilder getDataOrBuilder(
      int index);
}
