// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remotedb.proto

package com.wangao.dd.protohelper;

public interface RemoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sql = 1;</code>
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 1;</code>
   */
  com.google.protobuf.ByteString
      getSqlBytes();
}
