// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remotedb.proto

package com.wangao.dd.protohelper;

public final class Remotedb {
  private Remotedb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RemoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeyValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016remotedb.proto\"\034\n\rRemoteRequest\022\013\n\003sql" +
      "\030\001 \001(\t\"&\n\016RemoteResponse\022\024\n\004data\030\001 \003(\0132\006" +
      ".MyMap\"!\n\005MyMap\022\030\n\005entry\030\001 \003(\0132\t.KeyValu" +
      "e\"&\n\010KeyValue\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t27\n\rRemoteService\022&\n\003Get\022\016.RemoteReques" +
      "t\032\017.RemoteResponseB\035\n\031com.wangao.dd.prot" +
      "ohelperP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RemoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RemoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteRequest_descriptor,
        new java.lang.String[] { "Sql", });
    internal_static_RemoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RemoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RemoteResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_MyMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MyMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyMap_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeyValue_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
